/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.bits.ui;

import com.bits.ProductGroup;
import com.bits.services.ProductGroupService;
import com.bits.services.ProductService;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class ProductGroupInternalFrame extends javax.swing.JInternalFrame {
    ProductGroupTableModel model;
    
    /**
     * Creates new form ProductGroupInternalFrame
     */
    public ProductGroupInternalFrame() {
        model = new ProductGroupTableModel();
        ProductGroupService service = new ProductGroupService();
        model.productGroups = service.getAll();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codeInputField = new javax.swing.JTextField();
        nameInputField = new javax.swing.JTextField();
        saveButon = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productGroupTable = new javax.swing.JTable();
        deleteBtn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Product Group");

        jLabel1.setText("Group Code");

        jLabel2.setText("Group Name");

        saveButon.setText("Save");
        saveButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButonActionPerformed(evt);
            }
        });

        productGroupTable.setModel(model);
        jScrollPane1.setViewportView(productGroupTable);

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameInputField, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(codeInputField))
                        .addGap(18, 18, 18)
                        .addComponent(saveButon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteBtn)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(codeInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButon)
                    .addComponent(deleteBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButonActionPerformed
       if (codeInputField.getText().equals("") || nameInputField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Both code and name are required!");
        } else {
           ProductGroupService service = new ProductGroupService();
           ProductGroup productGroup = new ProductGroup(codeInputField.getText(), nameInputField.getText());
           
           try {
               service.save(productGroup);
           } catch (IOException ex) {
           }
           model.productGroups = service.getAll();
           model.fireTableDataChanged();
           codeInputField.setText("");
           nameInputField.setText("");
        }
    }//GEN-LAST:event_saveButonActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int row = productGroupTable.getSelectedRow();
        int value = (int) productGroupTable.getModel().getValueAt(row, 0);
        
        
        ProductGroupService productGroupService = new ProductGroupService();
        productGroupService.delete(value);
        model.productGroups = productGroupService.getAll();
        model.fireTableDataChanged();
    }//GEN-LAST:event_deleteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codeInputField;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameInputField;
    private javax.swing.JTable productGroupTable;
    private javax.swing.JButton saveButon;
    // End of variables declaration//GEN-END:variables
}
